MINIMUM_PARKING_INTERVAL_SECONDS = 15 * 60

lock = 1

parking_construct = [
    [
        [{
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }],
        [{
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }],
        [{
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }],
        [{
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }, {
            "size": 2,
            "handi": True,
            "available": True
        }],
        [{
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }],
        [{
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }, {
            "size": 1,
            "handi": False,
            "available": True
        }]
    ],
    [
        [{
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }],
        [{
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }],
        [{
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }],
        [{
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }],
        [{
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }],
        [{
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }],
        [{
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }],
        [{
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }]
    ],
    [
        [{
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }],
        [{
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }],
        [{
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }],
        [{
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }, {
            "size": 2,
            "handi": False,
            "available": True
        }],
        [{
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }],
        [{
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }],
        [{
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }],
        [{
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }, {
            "size": 3,
            "handi": False,
            "available": True
        }]
    ]
]

price_mapping = {
    1: 2.50,
    2: 5.00,
    3: 7.50
}
